### ISSUE TITLE
Mapped ports in docker for restate server doesn't seem to be picked up by `whoami` command

### ISSUE THREAD

**Issue by pksunkara** [restatedev/restate#1713]
Using the docker-compose config:

```yml
  restate:
    image: restatedev/restate
    ports:
      - 9070:9070
      - 9071:9071
      - 9072:8080
    extra_hosts:
      - host.docker.internal:host-gateway
```

Running `restate whoami` gives me:

```
 Ingress base URL  http://localhost:8080/
 Admin base URL    http://localhost:9070/
```

**Comment by tillrohrmann** [comment]
Hey @pksunkara. Thanks for reporting this issue. 

The Restate CLI does retrieve the values for the ingress and admin base URL from its configuration. You can find the different ways how to configure the CLI [here](https://docs.restate.dev/operate/configuration/cli/#using-environment-variables). So if you want to connect to a cluster whose admin endpoint runs on port 9099, then you could, for example, set `RESTATE_ADMIN_URL=http://localhost:9099`.

Does this resolve the issue?

**Comment by pksunkara** [comment]
Since I didn't change the admin url, restate cli did connect to the server. I guess I assumed it would read the ingress URL from the server. But what you said makes sense.

**Comment by pksunkara** [comment]
Hey, this seems to be still a bug.

Here's the updated docker compose file:

```yml
  restate:
    container_name: jujubi-restate
    image: restatedev/restate:1.6
    ports:
      - 9069:9069
      - 9070:9070
    environment:
      RESTATE_INGRESS__BIND_PORT: 9069
      RESTATE_INGRESS__ADVERTISED_HOST: 127.0.0.1:9069
    extra_hosts:
      - host.docker.internal:host-gateway
```

And running `restate whoami` is giving me the following:

```
            Restate
       https://restate.dev/

 Ingress base URL  http://127.0.0.1:8080/
 Admin base URL    http://127.0.0.1:9070/

Local Environment
 Config Dir        /home/pksunkara/.config/restate (does not exist)
 Environment File  /home/pksunkara/.config/restate/environment (does not exist)
 Environment       local (source: default)
 Config File       /home/pksunkara/.config/restate/config.toml (does not exist)
 Loaded .env file  (NONE)

Restate CLI Build Information
 Version              1.6.2
 ...

✅ Admin Service 'http://127.0.0.1:9070/' is healthy!
 Advertised ingress address  http://127.0.0.1:9069/
```

Please see that the ingress urls at the top and bottom are different.
