### ISSUE TITLE
Config parsing error.

### ISSUE THREAD

**Issue by 10thfloor** [restatedev/restate#2183]
I'm trying to use the `config.toml` form the docs but `restate whoami` refuses to parse it, failing with the error: 
```
restate whoami

Error:TOML parse error at line 1, column 9
|
1 | roles = ["worker", "admin", "metadata-store"]
|         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
invalid type: sequence, expected a map
in root/.config/restate/config.tomlTOML file 
```

`linux-x86`
and MacOS 

Restate v1.1

**Comment by 10thfloor** [comment]
Also tried copy/pasting the content of `restate-server --dump-config` into the toml file and still get the same error.

**Comment by tillrohrmann** [comment]
Thanks for reporting this issue @10thfloor. `.config/restate/config.toml` is the configuration of the CLI where the CLI records environment information. The linked `config.toml` is the configuration for the server and won't be understood by the CLI. Normally you don't have to touch `.config/restate/config.toml` yourself. Instead, we recommend using the `restate config` subcommand to edit it.

If you want to configure the restate-server deployment, then you can start `restate-server --config <PATH_TO_SERVER_CONFIG>`. You can also configure the restate server passing environment variables. [Here](https://docs.restate.dev/operate/configuration/server) you can find a few more details.

**Comment by 10thfloor** [comment]
@tillrohrmann Thanks for the reply. It makes more sense now. 

I'm trying to self-host the restate server via the Docker image, on Fly.io. It's working however I can't invoke my services (deployed to AWS),  I was trying to figure out how to set the Environment ID for my deployment (to provide to the AWS trust-policy, for the restate-server invoker...

I realize now this is probably because there is not a documented procedure for setting up a production instance of restate-server, since this would defeat the purpose restate-cloud. :)

**Comment by tillrohrmann** [comment]
Glad to hear that you find Restate useful 😊 We try to continually improve it so that it becomes more powerful.

If you are referring to the environment ID used in Restate's CLI, then this is indeed only relevant if you are interacting with a cloud-managed Restate server.

While I haven't deployed Restate server on Fly.io, I think this deployment setup should be possible. You probably need to provide the credentials to the process to talk to your services running on AWS. Maybe this resource can help in setting things up: https://fly.io/blog/oidc-cloud-roles/. I am also pulling in @pcholakov who knows a lot more than I about AWS and how to set up the right credentials.

**Comment by 10thfloor** [comment]
Yes worked like a charm!
Using this `fly.toml` for the restate deployment on fly: 
```toml
app = "restate-server"
organization = "boxfactory"

[build]
image = "docker.io/restatedev/restate:1.1"

[vm]
size = "performance-2x"

[env]
AWS_ROLE_ARN = "arn:aws:iam::313969411467:role/FlyBoxFactoryLambdaInvoker"
AWS_REGION = "us-east-1"

[mounts]
source = "restate_data"
destination = "/restate-data"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = "suspend"
auto_start_machines = true
min_machines_running = 0
[http_service.concurrency]
type = "requests"
soft_limit = 200
hard_limit = 250

# Node-ctrl port (gRPC + HTTP metrics)
[[services]]
internal_port = 5122
protocol = "tcp"
[[services.ports]]
handlers = ["http"]
port = 5122

# Metadata store (gRPC)
[[services]]
internal_port = 5123
protocol = "tcp"
[[services.ports]]
handlers = ["http"]
port = 5123

# Admin REST API
[[services]]
internal_port = 9070
protocol = "tcp"
[[services.ports]]
handlers = ["tls", "http"]
port = 9070

# Postgres protocol
[[services]]
internal_port = 9071
protocol = "tcp"
[[services.ports]]
handlers = ["pg_tls"]
port = 9071
```
Couldn't be easier. Plop that file into a directory and run `fly deploy`. Wait 2 minutes and it's up and running. Had to use a higher memory machine to accommodate `restate-server` process, the basic machine didn't have enough memory, so this is running on `performance-2x` machine, but this is probably overkill. 1GB `volume` for `restate-data` ...

8080 is the invocation endpoint, so I added the load balancer there. Not sure if all these ports need to be exposed to public internet.

OIDC setup with Fly/AWS was SUPER straightforward. Added permission to invoke lambdas in my account, and I'm off to the races. 

As simple as it gets.
