### ISSUE TITLE
Docker Compose documentation #documentation

### ISSUE THREAD

**Issue by dev-artisan** [restatedev/restate#2675]
Hi, thanks for the great work.
I wanted to suggest an addition to the documentation for docker, specifically that the restate server doesn't persist data by default and requires the volume mapped (the location of the volume) and the hostname also set.

Please see the discussion on discord here:
https://discord.com/channels/1128210118216007792/1306272565186138192

The sample docker compose file below is working for me

```
services:
  restate-server:
    container_name: restate-server
    hostname: restate-host
    image: docker.io/restatedev/restate:1.1
    ports:
      - 8080:8080
      - 9070:9070
      - 9071:9071
    environment:
      - RESTATE_TRACING_ENDPOINT=http://host.docker.internal:4317
    volumes:
      - /$HOME/restate/data/:/restate-data
    extra_hosts:
      - "host.docker.internal:host-gateway"
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.46
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - 4317:4317
      - 16686:16686
```
