### ISSUE TITLE
Using EKS Pod Identity credentials with Restate

### ISSUE THREAD

**Issue by devfacet** [restatedev/restate#3363]
I'm trying to use [EKS Pod Identity](https://docs.aws.amazon.com/eks/latest/userguide/pod-id-how-it-works.html) with my Restate cluster. I've a cluster configuration like below:

```toml
auto-provision = false

[metadata-server]
type = "replicated"

[metadata-client]
addresses = ["http://restate:5122/"]

[worker.snapshots]
destination = "s3://REDACTED/restate/snapshots"
snapshot-interval-num-records = 1000
```

The cluster works without S3 worker snapshots. But it starts throwing errors as soon as I add worker snapshots config:

```shell
{"timestamp":"2025-06-06T15:26:28.886392Z","level":"WARN","fields":{"message":"provider failed to provide credentials","provider":"EcsContainer","error":"an error occurred while loading credentials: Non-success status from HTTP credential provider: StatusCode(400) (ProviderError(ProviderError { source: \"Non-success status from HTTP credential provider: StatusCode(400)\" }))"},"target":"aws_config::meta::credentials::chain"}
{"timestamp":"2025-06-06T15:26:28.886443Z","level":"ERROR","fields":{"error":"The operation lacked valid authentication credentials for path <n/a>: an error occurred while loading credentials"},"target":"restate_worker::partition::snapshots::repository"}
{"timestamp":"2025-06-06T15:26:28.887019Z","level":"WARN","fields":{"message":"Partition processor exited unexpectedly","err":"The operation lacked valid authentication credentials for path <n/a>: an error occurred while loading credentials"},"target":"restate_worker::partition_processor_manager"}
```

I can confirm `AWS_CONTAINER_CREDENTIALS_FULL_URI` and `AWS_CONTAINER_AUTHORIZATION_TOKEN_FILE` env variables are injected to the Restate cluster pods.

[The SDK documentation](https://docs.aws.amazon.com/eks/latest/userguide/pod-id-minimum-sdk.html) says:

> To use the credentials from a EKS Pod Identity association, your code can use any AWS SDK to create a client for an AWS service with an SDK, and by default the SDK searches in a chain of locations for AWS Identity and Access Management credentials to use. The EKS Pod Identity credentials will be used if you don’t specify a credential provider when you create the client or otherwise initialized the SDK.

> This works because EKS Pod Identities have been added to the Container credential provider which is searched in a step in the default credential chain. If your workloads currently use credentials that are earlier in the chain of credentials, those credentials will continue to be used even if you configure an EKS Pod Identity association for the same workload.

> Make sure that you’re using the following versions, or later, for your AWS SDK
> Rust – [release-2024-03-13](https://github.com/awslabs/aws-sdk-rust/releases/tag/release-2024-03-13)

any thoughts?

**Comment by tillrohrmann** [comment]
Hey @devfacet, did you try setting EKS pod identity up as described [here](https://aws.amazon.com/blogs/aws/amazon-eks-pod-identity-simplifies-iam-permissions-for-applications-on-amazon-eks-clusters/) or did you follow a different guide? How did you set up the associated IAM role and its trust policy?

@pcholakov do you have an idea what could be causing the problem?

**Comment by pcholakov** [comment]
We should definitely be picking these up without any special config, based on the default SDK credential chain. This works for us on ECS but I don’t believe we’ve specifically tested snapshots from EKS anywhere - let me test and come back to you.

**Comment by pcholakov** [comment]
@devfacet, this error is [coming from the AWS credential provider](https://github.com/awslabs/aws-sdk-rust/blob/c5ee364f638b7ae400ad440c36f8d74d3f41d489/sdk/aws-config/src/meta/credentials/chain.rs#L105) on which we rely. Can you please try run Restate with the following log settings which might tell us more:

`RUST_LOG`: `"aws_config=debug,restate_object_store_util=debug,info"`

You can also set this via the root `log-filter` key in the Restate `config.toml` configuration file, if you use one.

**Comment by jackkleeman** [comment]
EKS Pod Identity is used in Restate Cloud and at least there, it is picked up automatically by the restate pod without any extra config

**Comment by pcholakov** [comment]
Hey @devfacet, were you able to get some debug logs or any other insights into the issue?

**Comment by devfacet** [comment]
I apologize for my late reply, I was busy with some other issues.

@tillrohrmann: I'm using https://registry.terraform.io/modules/terraform-aws-modules/eks-pod-identity/aws/1.12.0 I can confirm that:

1. The IAM role is created with the trust entity:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Service": "pods.eks.amazonaws.com"
            },
            "Action": [
                "sts:TagSession",
                "sts:AssumeRole"
            ],
            "Condition": {
                "StringEquals": {
                    "aws:PrincipalOrgID": "o-$REDACTED"
                }
            }
        }
    ]
}
```

2. The IAM role has the following policy is attached:

```json
{
    "Statement": [
        {
            "Action": [
                "s3:ListBucket",
                "s3:GetObject",
                "s3:PutObject",
                "s3:ListObjectsV2"
            ],
            "Effect": "Allow",
            "Resource": [
                "arn:aws:s3:::$REDACTED",
                "arn:aws:s3:::$REDACTED/*"
            ]
        }
    ],
    "Version": "2012-10-17"
}
```

3. EKS cluster "Pod Identity associations" shows correct namespace and service accounts.

```shell
aws eks list-pod-identity-associations --cluster-name dev --namespace restate-test --service-account restate
{
    "associations": [
        {
            "clusterName": "dev",
            "namespace": "restate-test",
            "serviceAccount": "restate",
            "associationArn": "arn:aws:eks:us-east-1:$REDACTED$:podidentityassociation/dev/a-$REDACTED",
            "associationId": "a-$REDACTED"
        }
    ]
}
```

@pcholakov @jackkleeman : EKS pods have the following env variables:

```yaml
        - name: RUST_LOG
          value: aws_config=debug,restate_object_store_util=debug,info
        - name: AWS_DEFAULT_REGION
          value: us-east-1
        - name: AWS_STS_REGIONAL_ENDPOINTS
          value: regional
        - name: AWS_CONTAINER_CREDENTIALS_FULL_URI
          value: http://169.254.170.23/v1/credentials
        - name: AWS_CONTAINER_AUTHORIZATION_TOKEN_FILE
          value: >-
            /var/run/secrets/pods.eks.amazonaws.com/serviceaccount/eks-pod-identity-token
```

and volume mounts:

```yaml
        - name: eks-pod-identity-token
          readOnly: true
          mountPath: /var/run/secrets/pods.eks.amazonaws.com/serviceaccount
```

I can confirm the token file in the restate pods:

```shell
restate-0:/$ ls -l /var/run/secrets/pods.eks.amazonaws.com/serviceaccount/eks-pod-identity-token
lrwxrwxrwx. 1 root 2000 29 Jun 22 19:01 /var/run/secrets/pods.eks.amazonaws.com/serviceaccount/eks-pod-identity-token -> ..data/eks-pod-identity-token
```

I use https://github.com/restatedev/restate-operator to deploy the Restate cluster. The following definition works when I add `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` to the env section. But it doesn't work when it's like below:

```yaml
apiVersion: restate.dev/v1
kind: RestateCluster
metadata:
  name: restate-test # a namespace with the same name as the RestateCluster will be created
spec:
  clusterName: restate
  compute:
    replicas: 3
    image: restatedev/restate:1.3.2
    env:
      - name: RUST_LOG
        value: "aws_config=debug,restate_object_store_util=debug,info"
      - name: AWS_DEFAULT_REGION
        value: us-east-1

  storage:
    storageClassName: gp3
    storageRequestBytes: 10737418240 # 10 GiB

  security:
    serviceAccountAnnotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::$REDACTED:role/eks-dev-restate-cluster-test-20250622170832696900000002

  # Refs: https://docs.restate.dev/guides/local-to-replicated/
  #       https://github.com/restatedev/restate-operator/tree/main
  config: |
    roles = [
      "worker",
      "admin",
      "log-server"
    ]
    auto-provision = true
    default-num-partitions = 128
    default-replication = 2

    # Object store for metadata
    [metadata-client]
    type = "object-store"
    path = "s3://$REDACTED/restate-test/metadata"

    # Raft based metadata store
    # Add "metadata-server" to roles
    # [metadata-client]
    # addresses = ["http://restate:5122/"]
    # [metadata-server]
    # type = "replicated"

    [bifrost]
    default-provider = "replicated"

    [worker.snapshots]
    destination = "s3://$REDACTED/restate-test/snapshots"
    snapshot-interval-num-records = 10000

    [worker.invoker]
    inactivity-timeout = "5m"
    abort-timeout = "5m"
```

Here is the error:

```shell
+ restate-0 › restate
restate-0 restate {"timestamp":"2025-06-22T19:01:29.400352Z","level":"INFO","fields":{"message":"Starting Restate Server 1.3.2 (e554bc0 x86_64-unknown-linux-gnu 2025-04-18)","node_name":"restate-0","config_source":"/config/config.toml","base_dir":"/restate-data/restate-0/"},"target":"restate_server"}
restate-0 restate {"timestamp":"2025-06-22T19:01:29.418655Z","level":"DEBUG","fields":{"message":"Using AWS SDK credentials provider","region":"Region(\"us-east-1\")"},"target":"restate_object_store_util"}
restate-0 restate {"timestamp":"2025-06-22T19:01:29.506989Z","level":"DEBUG","fields":{"message":"Using AWS SDK credentials provider","region":"Region(\"us-east-1\")"},"target":"restate_object_store_util"}
restate-0 restate {"timestamp":"2025-06-22T19:01:29.514547Z","level":"INFO","fields":{"message":"Server listening"},"target":"restate_core::network::net_util","span":{"net.host.addr":"0.0.0.0","net.host.port":5122,"server_name":"node-rpc-server","name":"server"},"spans":[{"net.host.addr":"0.0.0.0","net.host.port":5122,"server_name":"node-rpc-server","name":"server"}]}
restate-0 restate {"timestamp":"2025-06-22T19:01:29.514615Z","level":"INFO","fields":{"message":"Trying to join the cluster 'restate'"},"target":"restate_node::init"}
restate-0 restate {"timestamp":"2025-06-22T19:01:29.514848Z","level":"DEBUG","fields":{"message":"provider in chain did not provide credentials","provider":"Environment","context":"the credential provider was not enabled: environment variable not set (CredentialsNotLoaded(CredentialsNotLoaded { source: Some(\"environment variable not set\") }))"},"target":"aws_config::meta::credentials::chain","span":{"provider":"default_chain","name":"provide_credentials"},"spans":[{"provider":"default_chain","name":"provide_credentials"}]}
restate-0 restate {"timestamp":"2025-06-22T19:01:29.514885Z","level":"DEBUG","fields":{"message":"provider in chain did not provide credentials","provider":"Profile","context":"the credential provider was not enabled (CredentialsNotLoaded(CredentialsNotLoaded { source: None }))"},"target":"aws_config::meta::credentials::chain","span":{"provider":"default_chain","name":"provide_credentials"},"spans":[{"provider":"default_chain","name":"provide_credentials"}]}
restate-0 restate {"timestamp":"2025-06-22T19:01:29.514909Z","level":"DEBUG","fields":{"message":"provider in chain did not provide credentials","provider":"WebIdentityToken","context":"the credential provider was not enabled: $AWS_WEB_IDENTITY_TOKEN_FILE was not set (CredentialsNotLoaded(CredentialsNotLoaded { source: Some(\"$AWS_WEB_IDENTITY_TOKEN_FILE was not set\") }))"},"target":"aws_config::meta::credentials::chain","span":{"provider":"default_chain","name":"provide_credentials"},"spans":[{"provider":"default_chain","name":"provide_credentials"}]}
restate-0 restate {"timestamp":"2025-06-22T19:01:29.596549Z","level":"WARN","fields":{"message":"provider failed to provide credentials","provider":"EcsContainer","error":"an error occurred while loading credentials: Non-success status from HTTP credential provider: StatusCode(400) (ProviderError(ProviderError { source: \"Non-success status from HTTP credential provider: StatusCode(400)\" }))"},"target":"aws_config::meta::credentials::chain","span":{"provider":"default_chain","name":"provide_credentials"},"spans":[{"provider":"default_chain","name":"provide_credentials"}]}
restate-0 restate {"timestamp":"2025-06-22T19:01:29.596750Z","level":"DEBUG","fields":{"message":"provider in chain did not provide credentials","provider":"Environment","context":"the credential provider was not enabled: environment variable not set (CredentialsNotLoaded(CredentialsNotLoaded { source: Some(\"environment variable not set\") }))"},"target":"aws_config::meta::credentials::chain","span":{"provider":"default_chain","name":"provide_credentials"},"spans":[{"provider":"default_chain","name":"provide_credentials"}]}
restate-0 restate {"timestamp":"2025-06-22T19:01:29.596816Z","level":"DEBUG","fields":{"message":"provider in chain did not provide credentials","provider":"Profile","context":"the credential provider was not enabled (CredentialsNotLoaded(CredentialsNotLoaded { source: None }))"},"target":"aws_config::meta::credentials::chain","span":{"provider":"default_chain","name":"provide_credentials"},"spans":[{"provider":"default_chain","name":"provide_credentials"}]}
...
```

Please let me know what else I can do for debugging further.

Thanks
